### ISSUE TITLE
How can I add a Logo to the front end? I edited the index.hbs and it does not show on the browser.

### ISSUE THREAD

**Issue by Leadspie** [sammy007/open-ethereum-pool#188]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````

**Comment by Coinizy1** [comment]
After changing the logo. gogo open-ethereum-pool/www/:
and run
./build.sh

**Comment by Leadspie** [comment]
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (preprocessedApp & templates)] failed with:
Error: Closing tag `p` (on line 31) did not match last open tag `span` (on line 30).
    at validateEndTag (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:17345:13)
    at Parser.exports.default.finishEndTag (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:17206:7)
    at Parser.exports.default.finishTag (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:17182:14)
    at Object.EventedTokenizer.states.tagName (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:19154:25)
    at Object.EventedTokenizer.tokenizePart (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:18965:33)
    at Parser.exports.default.ContentStatement (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:16973:22)
    at Parser.acceptNode (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:16819:27)
    at Parser.exports.default.Program (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:16877:14)
    at Parser.acceptNode (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:16819:27)
    at Object.preprocess (/home/cmilian/open-ethereum-pool/www/bower_components/ember/ember-template-compiler.js:16778:46)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/home/cmilian/open-ethereum-pool/www/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/cmilian/open-ethereum-pool/www/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/home/cmilian/open-ethereum-pool/www/node_modules/broccoli-merge-trees/index.js:36:53)
    at module.exports (/home/cmilian/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp.appAndDependencies (/home/cmilian/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1078:44)
    at EmberApp.javascript (/home/cmilian/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1216:34)
    at EmberApp.toArray (/home/cmilian/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1640:10)
    at EmberApp.toTree (/home/cmilian/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:30)
    at module.exports (/home/cmilian/open-ethereum-pool/www/ember-cli-build.js:35:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/home/cmilian/open-ethereum-pool/www/node_modules/ember-cli/lib/models/builder.js:70:19)

```

**Comment by Coinizy1** [comment]
Did you manage to run it ?
thanks

**Comment by Leadspie** [comment]
Yes I did, missing tag. https://ethepool.com

**Comment by Coinizy1** [comment]
Can you tell me one thing
What address to use in geth with --unlock
The address i created with geth account new?
Thanks

**Comment by Coinizy1** [comment]
And which missing tag?
Thanks

**Comment by Leadspie** [comment]
The missing tag was in the content I added in the front end. 

Yes, that address. 

Carmelo Milian
CEO at OneCloud
Http://OneCloudOps.com

**Comment by Leadspie** [comment]
Yes, that address. It was a missing tag from the content I added in the front end.

**Comment by Coinizy1** [comment]
And which address to add in
Unlocker (
And
Payout
Config.json

**Comment by mikeyb** [comment]
yours, obviously
