### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by bapparabi** [sammy007/open-ethereum-pool#238]
do you know how to solve this iisue 

root@pirl:/home/mining/open-ethereum-pool/www# ./build.sh

/home/mining/open-ethereum-pool/www/node_modules/ember-cli-app-version/node_modules/ember-cli-babel/index.js:4
const VersionChecker = require('ember-cli-version-checker');
^^^^^
Use of const in strict mode.
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.Addon.lookup (/home/mining/open-ethereum-pool/www/node_modules/ember-cli/lib/models/addon.js:998:19)
    at /home/mining/open-ethereum-pool/www/node_modules/ember-cli/lib/models/addons-factory.js:48:38
    at visit (/home/mining/open-ethereum-pool/www/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/home/mining/open-ethereum-pool/www/node_modules/ember-cli/lib/utilities/DAG.js:137:7)
root@pirl:/home/mining/open-ethereum-pool/www#

**Comment by mikeyb** [comment]
Google the error....

**Comment by sammy007** [comment]
It must not happen, you seems installed wrong version of ember-cli. I need to update it to the latest LTS soon.

**Comment by rainmetersjtu** [comment]
got the same error。ember-cli version is 2.9.1 ├─┬ ember-cli@2.9.1
