### ISSUE TITLE
-bash: ./config.json: Permission denied

### ISSUE THREAD

**Issue by ahrcoin** [sammy007/open-ethereum-pool#262]
#### System information

Geth version: parity

Redis version:  v=3.0.6

OS & Version: Linux

Trying to run the pool using ./build/bin/open-ethereum-pool config.json and i get file does not exist  When i try to ./config.json in the open-ethereum-pool directory I get permission denied.  I can get everything else running ember, parity node, etc. but don't know if i am doing anything else wrong.

Sorry i am pretty new to this.  Probably a dumb question.  I am just trying to set up a mining server for me and a buddy.  And trying to learn as I go.

**Comment by ahrcoin** [comment]
Well i had it working using ./build/bin/open-ethereum-pool config.json

then i got this error:
Error: ENOENT: no such file or directory, stat '/home/ubuntu/open-ethereum-pool/www/tmp/simple_concat-input_base_path-WHlbsomK.tmp/0/vendor/jquery-cookie/jquery.cookie.js'

I deleted everything and started over doing exactly what i did before and now the ./build/bin/open-ethereum-pool config.json is not working again.  It is like Ember is not creating this path to start the pool.

**Comment by mikeyb** [comment]
https://github.com/sammy007/open-ethereum-pool/search?q=ENOENT&type=Issues

hmmm

**Comment by ahrcoin** [comment]
Am I at least correct in my thinking that ember creates that path once you run it? Or does the ./build.sh create that path?

**Comment by ahrcoin** [comment]
Now I can't get past the ./build.sh...... keep getting:

root@localhost:~/open-ethereum-pool/www# ./build.sh
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, stat '/root/open-ethereum-pool/www/tmp/simple_concat-input_base_path-Lw81fwBR.tmp/0/vendor/jquery-cookie/jquery.cookie.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at FSMonitor._measure (/root/open-ethereum-pool/www/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.statSync (/root/open-ethereum-pool/www/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at Concat.keyForFile (/root/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/root/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:109:65)
    at /root/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/root/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/root/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:538:13)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/root/open-ethereum-pool/www/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/root/open-ethereum-pool/www/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/root/open-ethereum-pool/www/node_modules/broccoli-merge-trees/index.js:36:53)
    at module.exports (/root/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp.javascript (/root/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1278:10)
    at EmberApp.toArray (/root/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1640:10)
    at EmberApp.toTree (/root/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:30)
    at module.exports (/root/open-ethereum-pool/www/ember-cli-build.js:35:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/root/open-ethereum-pool/www/node_modules/ember-cli/lib/models/builder.js:70:19)
    at CoreObject.module.exports.Task.extend.init (/root/open-ethereum-pool/www/node_modules/ember-cli/lib/models/builder.js:50:10)
