### ISSUE TITLE
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:

### ISSUE THREAD

**Issue by bapparabi** [sammy007/open-ethereum-pool#280]
when i try to use the ./build.sh command i am getting this error 

do you what is the issue and how to solve it 

`Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, stat '/home/pooladmin/open-ethereum-pool/www/tmp/simple_concat-input_base_path-GZGs4cD3.tmp/0/vendor/jquery-cookie/jquery.cookie.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at FSMonitor._measure (/home/pooladmin/open-ethereum-pool/www/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.statSync (/home/pooladmin/open-ethereum-pool/www/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at Concat.keyForFile (/home/pooladmin/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/home/pooladmin/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:109:65)
    at /home/pooladmin/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/home/pooladmin/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/pooladmin/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:538:13)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/home/pooladmin/open-ethereum-pool/www/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/pooladmin/open-ethereum-pool/www/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/home/pooladmin/open-ethereum-pool/www/node_modules/broccoli-merge-trees/index.js:36:53)
    at module.exports (/home/pooladmin/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp.javascript (/home/pooladmin/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1278:10)
    at EmberApp.toArray (/home/pooladmin/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1640:10)
    at EmberApp.toTree (/home/pooladmin/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:30)
    at module.exports (/home/pooladmin/open-ethereum-pool/www/ember-cli-build.js:35:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/home/pooladmin/open-ethereum-pool/www/node_modules/ember-cli/lib/models/builder.js:70:19)
    at CoreObject.module.exports.Task.extend.init (/home/pooladmin/open-ethereum-pool/www/node_modules/ember-cli/lib/models/builder.js:50:10)
`

**Comment by mikeyb** [comment]
CLOSE
