### ISSUE TITLE
Parity + config.json ERROR

### ISSUE THREAD

**Issue by jrischma** [sammy007/open-ethereum-pool#340]
#### System information

Parity/v1.11.0-beta-62ccdd7-20180508/x86_64-linux-gnu/rustc1.25.0

Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=c59cc13e863d4f5c

OS & Version: Linux/16.04 

 ./open-ethereum-pool pool.json

2018/05/10 03:09:15 Loading config: /home/ethereum/open-ethereum-pool/build/bin/pool.json
2018/05/10 03:09:15 Running with 2 threads
2018/05/10 03:09:15 Backend check reply: PONG
2018/05/10 03:09:15 Policy state refresh complete
2018/05/10 03:09:15 Set policy stats reset every 1h0m0s
2018/05/10 03:09:15 Set policy state refresh every 1m0s
2018/05/10 03:09:15 Running with 8 policy workers
2018/05/10 03:09:15 Upstream: main => http://127.0.0.1:8545
2018/05/10 03:09:15 Upstream: backup => http://127.0.0.2:8545
2018/05/10 03:09:15 Default upstream: main => http://127.0.0.1:8545
2018/05/10 03:09:15 Stratum listening on 0.0.0.0:8008
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7780c7]

goroutine 7 [running]:
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).fetchPendingBlock(0xc420138090, 0x60, 0x44, 0x0, 0x0, 0x0)
        /home/ethereum/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/blocks.go:106 +0x1a7
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).fetchBlockTemplate(0xc420138090)
        /home/ethereum/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/blocks.go:52 +0xe4
github.com/sammy007/open-ethereum-pool/proxy.NewProxy(0xcd57c0, 0xc4200e2d60, 0xc420102280)
        /home/ethereum/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/proxy.go:70 +0x4c4
main.startProxy()
        /home/ethereum/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/main.go:26 +0x39
created by main.main
        /home/ethereum/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/main.go:94 +0x275

please help, thanks

**Comment by Devil-of-Chaos** [comment]
Use Parity stable

**Comment by arokapil** [comment]
facing same issue 
with parity and geth both..
this has happened all of sudden

**Comment by djsmoke2018** [comment]
i also have this problem. i use stable version

**Comment by MCrypto** [comment]
had the same issue and found a post here about using the development branch which handles the changes in parity, so try the development branch

**Comment by stone212** [comment]
@MCrypto Can you point to that post?  I did not find it and today I have this error for the first time.  I am using Parity 1.11.8 stable.

**Comment by MCrypto** [comment]
@stone212 ... very sorry for taking some time to answer (was disconnected for a bit) ... I can't find the thread I read in (but it's somewhere here) ... in all cases these are the steps I used to compile for parity

you clone the repo normally and then switch to the develop branch and pull it and compile that (not sure that this is the most efficient way to get the develop branch but it's the one i know ... I'm not very good with using git commands!!):

> git clone https://github.com/sammy007/open-ethereum-pool.git
> cd open-ethereum-pool

list branches
> git branch -a

switch to develop branch
> git checkout -b develop remotes/origin/develop

pull it
> git fetch

and then compile it with normal method
> make

hope this helps!

**Comment by stone212** [comment]
@MCrypto No problem I only asked yesterday.  I just wanted to know the exact name of the branch.  I got it working by doing a fresh pull.  So thank you for getting me on the right direction.

**Comment by MCrypto** [comment]
@stone212 let us know how it went .... I actually changed from using parity so did not run the pool after all!

**Comment by stone212** [comment]
@MCrypto As I said I got it working by doing a fresh pull from develop branch.

**Comment by MCrypto** [comment]
@stone212  ... I was actually asking how it is working ... stable ... payments are working ... etc .... but I'm glad you got it working ... eventually I will give parity another go, especially when I look back into ELLA!

**Comment by stone212** [comment]
@MCrypto Okay yes.  It is working, payouts seem to work.  Miners connect.  Everything seems normal.  I don't know what ELLA is but I think Parity is better than Geth in many ways personally.  It has bugs butit is very good and the Parity team works to fix the bugs.
