### ISSUE TITLE
pool run error  : while refreshing block template on main: not supported

### ISSUE THREAD

**Issue by kissxrl** [sammy007/open-ethereum-pool#441]
`./build/bin/open-ethereum-pool config.json`

![111111111111111](https://user-images.githubusercontent.com/9613121/62009015-7e0f9900-b18c-11e9-8f8f-8b002fdc62c9.png)

`Altcoins  RPC`
![22222222222222222222](https://user-images.githubusercontent.com/9613121/62009037-f8401d80-b18c-11e9-9550-4a42a34ce39d.png)

> eth.getWork()
Error: not supported
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

**Comment by pool2mine** [comment]
Did you added “—mine” when you run geth?

**Comment by kissxrl** [comment]
> Did you added “—mine” when you run geth?

yes 

`--rpc --mine --rpcapi "eth,web3,admin,personal,net" --rpcaddr 0.0.0.0 --rpcport "8545"`

**Comment by kissxrl** [comment]
> Did you added “—mine” when you run geth?

This is gvccoin. He's an eth imitator.

`https://github.com/cryptozoic-io/support/blob/master/downloads/gvc/gvc-stable-0.2.4.tar`

**Comment by huglester** [comment]
Did you solve this? 
@kissxrl find me on telegram with same username
