### ISSUE TITLE
Cannot find module 'serialize-javascript'

### ISSUE THREAD

**Issue by skygong** [sammy007/open-ethereum-pool#53]
"npm install -g ember-cli@2.4.3
npm install -g bower
npm install
bower install"
all right!
but execute instruction  ./build.sh

root@ubuntu:~/open-ethereum-pool/www# ./build.sh
Cannot find module 'serialize-javascript'
Error: Cannot find module 'serialize-javascript'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/open-ethereum-pool/www/node_modules/ember-intl/index.js:10:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by sammy007** [comment]
Works for me with nodejs `4.2.6` on ubuntu 16.06 LTS. Just tested.

PS: Stop opening issues with nonsense title.
