### ISSUE TITLE
Building Failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by NoMoSnacks** [sammy007/open-ethereum-pool#60]
#### System information

Geth version: `5f55d95`

Redis version: `Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42`

OS & Version: Linux 16.04 LTS

Commit branch and hash: `master`, `77d8a35`
#### Expected behaviour

Completion of Build
#### Actual behaviour

Build Failing
#### Steps to reproduce the behaviour

Followed Build Instructions:
sudo npm install -g ember-cli@2.4.3
sudo npm install -g bower
npm install
bower install
./build.sh
#### Backtrace

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Build failed.
The Broccoli Plugin: [SimpleConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/home/ubuntu/open-ethereum-pool/www/tmp/simple_concat-input_base_path-WHlbsomK.tmp/0/vendor/jquery-cookie/jquery.cookie.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:109:65)
    at /home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ConcatWithMaps (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-concat/concat.js:24:17)
    at module.exports (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:346:10)
    at EmberApp.javascript (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1212:12)
    at EmberApp.toArray (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)
    at EmberApp.toTree (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/home/ubuntu/open-ethereum-pool/www/ember-cli-build.js:35:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/models/builder.js:55:19)

```

**Comment by sammy007** [comment]
Works for me on the same setup. Try to remove `tmp` and run `./build.sh` again.

**Comment by NoMoSnacks** [comment]
```
ubuntu:~/open-ethereum-pool/www$ ls
app  bower_components  bower.json  build.sh  config  ember-cli-build.js  node_modules  package.json  public  README.md  testem.json  tests  tmp  translations  vendor
ubuntu:~/open-ethereum-pool/www$ rm -rf tmp/
ubuntu:~/open-ethereum-pool/www$ ./build.sh
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Build failed.
The Broccoli Plugin: [SimpleConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/home/ubuntu/open-ethereum-pool/www/tmp/simple_concat-input_base_path-xo2NraP0.tmp/0/vendor/jquery-cookie/jquery.cookie.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:109:65)
    at /home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/ubuntu/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ConcatWithMaps (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-concat/concat.js:24:17)
    at module.exports (/home/ubuntu/open-ethereum-pool/www/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:346:10)
    at EmberApp.javascript (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1212:12)
    at EmberApp.toArray (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)
    at EmberApp.toTree (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/home/ubuntu/open-ethereum-pool/www/ember-cli-build.js:35:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/ubuntu/open-ethereum-pool/www/node_modules/ember-cli/lib/models/builder.js:55:19)
```

**Comment by NoMoSnacks** [comment]
This is a brand new AWS instance. I've only installed what I needed to build this.

**Comment by sammy007** [comment]
Weird. Try this:

```
rm -rf ./tmp
rm -rf ./node_modules
rm -rf ./bower_components
npm install
bower install
./build.sh
```

Also make sure that node version is `4.x`.

**Comment by NoMoSnacks** [comment]
That is very strange. Node is v4.4.7 and it failed again.

**Comment by sammy007** [comment]
Perhaps something is wrong during `npm install`. On my side it looks like:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global npm@2.14.21 should be installed with -g
npm WARN prefer global jshint@2.9.2 should be installed with -g

> ember-cli-cookie@0.2.0 postinstall /tmp/open-ethereum-pool/www/node_modules/ember-cli-cookie
> bower install --allow-root

bower jquery-cookie#~1.4.1      cached https://github.com/carhartl/jquery-cookie.git#1.4.1
bower jquery-cookie#~1.4.1    validate 1.4.1 against https://github.com/carhartl/jquery-cookie.git#~1.4.1
bower jquery#>=1.2              cached https://github.com/jquery/jquery-dist.git#3.1.0
bower jquery#>=1.2            validate 3.1.0 against https://github.com/jquery/jquery-dist.git#>=1.2
bower jquery-cookie#~1.4.1     install jquery-cookie#1.4.1
bower jquery#>=1.2             install jquery#3.1.0

jquery-cookie#1.4.1 vendor-addon/jquery-cookie
└── jquery#3.1.0
...
```

Best I can suggest ATM is to just uninstall npm, install again and repeat all steps again.

**Comment by sammy007** [comment]
Also if you urgently need it build `dist` on your workstation and deploy. Make sure to specify correct `ApiUrl` in `config/environment.js`.

**Comment by NoMoSnacks** [comment]
I reset the AWS instance from scratch. This is the contents of my .bash_history starting from the first bootup of the instance:
```
sudo apt-get install software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install geth golang redis-server
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
git clone https://github.com/sammy007/open-ethereum-pool.git
cd open-ethereum-pool
make
sudo npm install -g ember-cli@2.4.3
sudo npm install -g bower
cd www/
npm install
bower install
./build.sh
```

`lsb_release -a` returns:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

Same error. I have no clue as to why it would work for others on the same setup yet fail for me, let me know if I missed a step. I appreciate the quick response as well, I am very grateful.


I don't understand what you mean by build dist. Is dist a package?

**Comment by sammy007** [comment]
I use stock node from Xenial: `sudo apt-get install nodejs npm`. Maybe something is wrong with nodesource package. Not a big node expert tbh.

> I don't understand what you mean by build dist. Is dist a package?

Frontend is a static single page website. All node stuff is required to build it into `ww/dist` directory which must be served by nginx or apache. You can build it on your workstation and move `dist` directory to server and configure nginx to serve it. Simple.

**Comment by NoMoSnacks** [comment]
My workstation is a windows box, so that would be difficult. I tried uninstalling the node and using stock but that also failed with the same error.

**Comment by NoMoSnacks** [comment]
I tried the build on a separate 14.04 LTS box and it worked. I still have no clue what the problem was.

**Comment by sammy007** [comment]
Looks like bower failed to install `jquery.cookie`.

**Comment by shenfeizi** [comment]
I am able to build open-ethereum-pool on Ubuntu 16.04 LTS following instructions in README. 
but my node is v.6.3.0. does this matter?

**Comment by sammy007** [comment]
No it does not.

**Comment by yt-bg** [comment]
Here is my working build sequence for Ubuntu 16.04:
`
apt-get install -y golang redis-server nodejs nginx npm
git clone https://github.com/sammy007/open-ethereum-pool
cd open-ethereum-pool/
make
nano config.json
cd www
nano config/environment.js
npm install -g ember-cli@2.4.3
npm install -g bower

cd /usr/bin
ln -s nodejs node      - not sure of needed
cd -

npm remove graceful-fs@3.0.8
npm install -g graceful-fs
npm install -g ember-cli-cookie
npm install ember-cli-cookie
bower install --allow-root
 ./build.sh
`

**Comment by mikeyb** [comment]
Ubuntu by default names the nodejs binary nodejs.  Most apps dependent on nodejs use the real binary name `node`.  The first thing you should do on ubuntu after installing nodejs is:

`sudo ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by sademat** [comment]
sudo ln -s /usr/bin/nodejs /usr/bin/node 

ln: failed to create symbolic link '/usr/bin/node': File exists

**Comment by sademat** [comment]
Anybody solve this problem

**Comment by sademat** [comment]
Here is my working build sequence for Ubuntu 16.04:

apt-get install -y golang redis-server nodejs nginx npm
git clone https://github.com/sammy007/open-ethereum-pool
cd open-ethereum-pool/
make
nano config.json
cd www
nano config/environment.js
npm install -g ember-cli@2.4.3
npm install -g bower
npm install

cd /usr/bin
ln -s nodejs node      (not sure if needed)
cd -

npm remove graceful-fs@3.0.8
npm install -g graceful-fs
npm install -g ember-cli-cookie (this may be not needed)
npm install ember-cli-cookie
bower install --allow-root
 ./build.sh

thanks!

**Comment by sammy007** [comment]
Updated ember to latest LTS today.

**Comment by yt-bg** [comment]
If

ln -s /usr/bin/nodejs /usr/bin/node

fails this means that your system has taken care of this before you. This
step is OK to fail.

**Comment by sammy007** [comment]
```
apt-cache search nodejs-legacy
nodejs-legacy - evented I/O for V8 javascript (legacy symlink)
```

**Comment by KL0nLutiy** [comment]
Hello, I have a problem, like this, how to solve it?
![image](https://cloud.githubusercontent.com/assets/5372884/22266827/263c6bd2-e28a-11e6-8629-6263206e1453.png)
Tried 
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
But it is not help.

**Comment by mikeyb** [comment]
what command is that from?

**Comment by KL0nLutiy** [comment]
From this one `npm install`

**Comment by Mrcoinzer** [comment]
how fix
ether@ubuntu:~/open-ethereum-pool$ make
build/env.sh go get -v ./...
github.com/sammy007/open-ethereum-pool/util
# github.com/sammy007/open-ethereum-pool/util
util/util.go:12: undefined: common.BigPow
util/util.go:39: undefined: common.BytesToBig
util/util.go:51: undefined: common.Ether
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sammy007** [comment]
@Mrcoinzer use develop branch for now.

**Comment by olegslT** [comment]
Change the ownership for the .config and cache directory

sudo chown -R username:username ~/.config 

and

sudo chown -R username:username ~/.cache
