### ISSUE TITLE
getting error during build.sh

### ISSUE THREAD

**Issue by robbmcmahan** [sammy007/open-ethereum-pool#70]
OS & Version: Linux/OSX
Ubuntu 16.x

I have successfully setup one server and was in the process of setting up a second for failover and am getting errors from the build.sh that I never received the first time around so I'm not sure if this is a regression or if there is just something different with the environment this time, however I did not have trouble the first time. ember-cli@2.4.3 and bower appeared to install fine (although I did have to use --allow-root to make that work)  I noticed that this time it also would only let me run build.sh with sudo. This is the error i'm getting:

Build failed.
The Broccoli Plugin: [SimpleConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/home/user/open-ethereum-pool/www/tmp/simple_concat-input_base_path-uBoZJO0b.tmp/0/vendor/jquery-cookie/jquery.cookie.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (/home/user/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/home/user/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:109:65)
    at /home/rmcmahan/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/user/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/user/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/user/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/home/user/open-ethereum-pool/www/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at: 
    at ConcatWithMaps.Plugin (/home/rmcmahan/open-ethereum-pool/www/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/home/rmcmahan/open-ethereum-pool/www/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ConcatWithMaps (/home/rmcmahan/open-ethereum-pool/www/node_modules/broccoli-concat/concat.js:24:17)
    at module.exports (/home/rmcmahan/open-ethereum-pool/www/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/home/rmcmahan/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:346:10)
    at EmberApp.javascript (/home/rmcmahan/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1212:12)
    at EmberApp.toArray (/home/rmcmahan/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)
    at EmberApp.toTree (/home/rmcmahan/open-ethereum-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/home/rmcmahan/open-ethereum-pool/www/ember-cli-build.js:35:14)
    at Class.module.exports.Task.ex

**Comment by robbmcmahan** [comment]
I was readling through an older issue that had to same problem and was resolved by installing on Ubuntu 14 so I tried that and getting a different error when building, now it can't find the module serialize-javascript

**Comment by robbmcmahan** [comment]
Ok, nevermind the last comment about serialize-json, apt-get installed a very old version of nodejs. I started over and getting the original error message about brocholli plugin even on Ubuntu 14

**Comment by boehla** [comment]
Also had this problem.

I fixed this with delete the whole folder and reclone.
Then execute in the fresh www folder:
```
sudo npm install -g ember-cli@2.4.3
sudo npm install -g bower
sudo npm install
bower install
sudo ./build.sh
```

**Comment by mikeyb** [comment]
Can this be closed now?
